---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kyteos
description: KyteOS - Custom KDE Plasma experience with gaming, emulation, and productivity tools.
base-image: quay.io/fedora-ostree-desktops/kinoite
image-version: "44"

modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
        - atim/lutris
        - atim/mangohud
    install:
      packages:
        - waydroid
        - wine
        - wine-core
        - gamemode
        - mangohud
        - podman
        - distrobox
        - btop
        - fastfetch
        - micro
        - starship
        - qt6-qtsvg
        - qt6-qtvirtualkeyboard
        - qt6-qtmultimedia
        - qt6-qtimageformats
        - papirus-icon-theme
        - capitaine-cursors
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - plasma-discover
        - plasma-discover-flatpak
        - plasma-discover-rpm-ostree
        - plasma-discover-packagekit

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - io.github.vencord.Vesktop
          - org.telegram.desktop
          - io.github.kolunmi.Bazaar
          - com.usebottles.bottles
          - net.davidotek.pupgui2
          - com.github.Matoking.protontricks
          - com.valvesoftware.Steam
          - com.heroicgameslauncher.hgl
          - net.lutris.Lutris
          - org.libretro.RetroArch
          - org.DolphinEmu.dolphin-emu
          - io.github.shiiion.primehack
          - org.pcsx2.PCSX2
          - net.rpcs3.RPCS3
          - org.ppsspp.PPSSPP
          - org.duckstation.DuckStation
          - org.xemu.xemu
          - org.sudachi_emu.sudachi
          - org.onlyoffice.desktopeditors
          - io.github.diegopvlk.Cine
          - xyz.nokarin.aqloss
          - de.haeckerfelix.Shortwave
          - com.transmissionbt.Transmission
          - org.kde.krita
          - com.github.tchx84.Flatseal
          - org.gufw.Gufw
          - io.github.flattool.Warehouse
          - com.ranfdev.DistroShelf
          - it.mijorus.gearlever
      - scope: user

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - scripts/install-silentsddm.sh

  - type: signing
